### ISSUE TITLE
Product - Reviews ordering - ReviewSortingCriterion - Q9

### ISSUE THREAD

**Issue by ljukas** [LiUGraphQL/LinGBM#33]
As in #32 we have differing schema and query template here.

We can query reviews on a product with the following:

`reviews(order:[ReviewSortingCriterion]): [Review]`

Here it says that we can pass a list of ReviewSortingCriterion to the order argument.

The only place this is used in a query template is in Q9 where it is used in the following way:

```
vendor(nr:$vendorID) {
    offers(limit:50) {
      product {
        reviews( order:{field:$attrReview direction:DESC} ) {
          title
          rating1
          rating2
          rating3
        }
      }
   }
}
```

Here the order argument is not a list, but a single object again. So I propse that we change the schema to the following:

`reviews(order:ReviewSortingCriterion): [Review]`

What are you thoughts?

**Comment by hartig** [comment]
As in my other comment (see https://github.com/LiUGraphQL/LinGBM/issues/32#issuecomment-505600686), to me the array-based approach seems to be more reasonable in general. However, this particular case here is a bit different than the case in #32, because here we really use only *one* ordering criterion in our query templates. Therefore, for this case, it seems easier to justify the single-object approach.

**Comment by chengsijin0817** [comment]
Thank, you are right. The array-based approach does give more possibility to some query, it seems that I tried to design more features than needed.
Based on our rule: only add exactly the features that are used in at least one of our query templates. You are right, I will check all issues related to 'array' or 'not array'.
I will let you know when I finished.

**Comment by chengsijin0817** [comment]
I have changed the schema to the single-object approach:
```
reviews(order:ReviewSortingCriterion): [Review]
```
