### ISSUE TITLE
It's LUBM not BSBM

### ISSUE THREAD

**Issue by VladimirAlexiev** [LiUGraphQL/LinGBM#79]
https://github.com/LiUGraphQL/LinGBM/blob/master/tools/datasetgen/README.md mentions https://sourceforge.net/projects/bsbmtools/, but the link underneath is https://github.com/rvesse/lubm-uba.

LinGBM is based on LUBM not BSBM (which is different) please fix the above link.

(This issue is mostly against myself: I don't know why I thought LinGBM is based on BSBM.
LUBM is a great basis, especially since it can produce both RDBMS and RDF)

**Comment by chengsijin0817** [comment]
Thanks. I have fixed the issue now (See commit #7d4c80c).
Please check it.

**Comment by VladimirAlexiev** [comment]
Ah, I misunderstood. I've read you extended the LUBM gen, but I thought that only related to outputting a GraphQL schema

**Comment by hartig** [comment]
> I've read you extended the LUBM gen, but I thought that only related to outputting a GraphQL schema

Note that our extended dataset generator does not output a GraphQL schema. Instead, the LinGBM GraphQL schema has been defined manually by us, and then we have defined [a mapping from that GraphQL schema to the RDB schema of the generated datasets](https://github.com/LiUGraphQL/LinGBM/wiki/Mapping-of-GraphQL-Schema-to-Relational-Schema-TODO) in order to specify how the GraphQL schema has to be implemented over the datasets. (Actually, I see now that the definition of this mapping is not complete yet.)
